config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

resources :warehouses do
  collection do
    post 'manage_roles'
    post 'delete_wu'
  end
  resources :inventories
end
resources :inventories do
  member do
    get 'move'
    post 'move'
  end
end

app/models/inventory.rb
class Inventory < ActiveRecord::Base
  unloadable

  include Redmine::SafeAttributes

  belongs_to :warehouse
  belongs_to :activity, :class_name => 'InventoryActivity', :foreign_key => 'activity_id'

  acts_as_customizable
  validates_presence_of :name, :warehouse_id
  validates_presence_of :status, :reason, :if => :check_moves
  safe_attributes 'type' , 'name' , 'description' ,
                  'part_number', 'date_in' , 'date_out' ,
                  'quantity', 'minimum_quantity',
                  'warehouse_id', 'activity_id',
                  'custom_field_values',
                  'custom_fields', 'status', 'reason'

  def check_moves
    return false if self.new_record?
    Inventory.find(self.id).warehouse_id != self.warehouse_id
  end

  def visible_custom_field_values(user=nil)
    user_real = user || User.current
    custom_field_values
  end

  def editable_custom_field_values(user=nil)
    visible_custom_field_values(user)
  end

  # Returns true if the attribute is required for user
  def required_attribute?(name, user=nil)
    required_attribute_names(user).include?(name.to_s)
  end

  def self.visible
    if User.current.admin?
      where(nil)
    else
      wu = WarehouseUser.where(user_id: User.current.id).pluck(:warehouse_id)
      Inventory.where(warehouse_id: wu)
    end
  end

  def editable_by?
    return true if User.current.admin?
    @can_edit ||= {}
    @can_edit[self.warehouse_id.to_s.to_sym] ||= WarehouseUser.where(user_id: User.current.id).where(warehouse_id: self.warehouse_id).where(can_manage:true).present?
  end
end

app/controllers/inventories_controller.rb
class InventoriesController < ApplicationController
  unloadable

  before_filter :get_warehouse
  before_filter :authorize_manage
  before_filter :get_inventory, only: [:edit, :update, :destroy, :show, :move]

  helper :custom_fields
  include CustomFieldsHelper
  helper :queries
  include QueriesHelper
  helper :sort
  include SortHelper

  def index
    @query = InventoryQuery.build_from_params(params, :name => '_')

    sort_init(@query.sort_criteria.empty? ? [['id', 'desc']] : @query.sort_criteria)
    sort_update(@query.sortable_columns)
    @query.sort_criteria = sort_criteria.to_a

    if @query.valid?
      case params[:format]
        when 'csv', 'pdf'
          @limit = Setting.issues_export_limit.to_i
          if params[:columns] == 'all'
            @query.column_names = @query.available_inline_columns.map(&:name)
          end
        when 'atom'
          @limit = Setting.feeds_limit.to_i
        when 'xml', 'json'
          @offset, @limit = api_offset_and_limit
          @query.column_names = %w(author)
        else
          @limit = per_page_option
      end
      scope = inventory_scope(:order => sort_clause)
      @entry_count = scope.count
      @entry_pages = Paginator.new @entry_count, per_page_option, params['page']
      @inventories = scope.offset(@entry_pages.offset).limit(@entry_pages.per_page).all
      render :layout => !request.xhr?
    else
      respond_to do |format|
        format.html { render(:template => 'issues/index', :layout => !request.xhr?) }
        format.any(:atom, :csv, :pdf) { render(:nothing => true) }
        format.api { render_validation_errors(@query) }
      end
    end
  rescue ActiveRecord::RecordNotFound
    render_404
  end


  def new
    if Warehouse.visible.blank?
      flash[:error] = "No Warehouse found"
      redirect_to warehouses_path
    end
    @inventory = Inventory.new
    if @warehouse
      @inventory.warehouse_id =  @warehouse.id
    end
  end

  def create
    @inventory = Inventory.new
    @inventory.safe_attributes = params[:inventory]
    if @inventory.save
      redirect_to warehouse_inventories_path(@inventory.warehouse)
    else
      render :new
    end
  end

  def move
    if request.post?
      @inventory.safe_attributes = params[:inventory]
      if @inventory.save
        redirect_to warehouse_inventories_path(@inventory.warehouse)
      else
        render :move
      end
    end
  end

  def show
  end


  def edit
  end

  def update
    @inventory.safe_attributes = params[:inventory]
    if @inventory.save
      redirect_to warehouse_inventories_path(@inventory.warehouse)
    else
      render :edit
    end
  end

  def destroy
    @inventory.destroy
    redirect_to inventories_path
  end

  private
  def get_inventory
    @inventory = Inventory.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    render_404
  end

  def get_warehouse
    if params[:warehouse_id]
      @warehouse = Warehouse.find(params[:warehouse_id])
    end
  rescue ActiveRecord::RecordNotFound
    render_404
  end

  def authorize_manage
    if params[:warehouse_id]
      deny_access unless @warehouse.editable_by?(User.current)
    end
  end

  def inventory_scope(options={})
    scope = @query.results_scope(options)

    scope
  end


end

app/helpers/inventories_helper.rb
module InventoriesHelper
end

app/views/inventories/_action_menu.html.erb
<div class="contextual">
  <% if params[:warehouse_id].nil? %>
      <% if params[:action] != 'index'%>
          <%= link_to( 'inventories', inventories_path)  %> |
      <% end %>
      <% if params[:action] != 'new'%>
          <%= link_to( 'new inventory', new_inventory_path(@warehouse) , class: 'icon icon-add')  %> |
      <% end %>
  <% else %>
      <% if params[:action] != 'index'%>
          <%= link_to( 'inventories', warehouse_inventories_path(@warehouse))  %> |
      <% end %>
      <% if params[:action] != 'new'%>
          <%= link_to( 'new inventory', new_warehouse_inventory_path(@warehouse), class: 'icon icon-add')  if params[:action] != 'new' %>
      <% end %>
  <% end %>

  <% if @inventory %>
      <%= link_to( 'Move', move_inventory_path(@inventory), class: 'icon icon-move') if params[:action].in? ['show', 'edit'] %>
  <% end %>
</div>

app/views/inventories/_attributes.html.erb
<%= labelled_fields_for :inventory, @inventory do |f| %>

    <div class="splitcontent">
      <div class="splitcontentleft">
        <% if @inventory.safe_attribute? 'activity_id' %>
            <p id="date_in_area">
              <%= f.select(:activity_id, options_for_select(InventoryActivity.all.map{|ia| [ia.name, ia.id] }, @inventory.activity_id ) ) %>
            </p>
        <% end %>
        <% if @inventory.safe_attribute? 'date_in' %>
            <p id="date_in_area">
              <%= f.text_field(:date_in, :size => 10) %>
              <%= calendar_for('inventory_date_in') %>
            </p>
        <% end %>

        <% if @inventory.safe_attribute? 'date_out' %>
            <p id="date_in_area">
              <%= f.text_field(:date_out, :size => 10) %>
              <%= calendar_for('inventory_date_out') %>
            </p>
        <% end %>

      </div>
      <div class="splitcontentright">
        <% if @inventory.safe_attribute? 'part_number' %>
            <p><%= f.text_field :part_number, :size => 4 %> </p>
        <% end %>
        <% if @inventory.safe_attribute? 'quantity' %>
            <p><%= f.number_field :quantity, :size => 4 %> </p>
        <% end %>
        <% if @inventory.safe_attribute? 'minimum_quantity' %>
            <p><%= f.number_field :minimum_quantity, :size => 4 %> </p>
        <% end %>
      </div>
    </div>

    <% if @inventory.safe_attribute? 'custom_field_values' %>
        <%= render :partial => 'form_custom_fields' %>
    <% end %>

<% end %>

<% include_calendar_headers_tags %>

app/views/inventories/_form.html.erb
<%= labelled_fields_for :inventory, @inventory do |f| %>
    <%= error_messages_for 'inventory' %>
    <% if @inventory.safe_attribute? 'warehouse_id' and @inventory.new_record? %>
        <p><%= f.select :warehouse_id,
                        options_for_select(Warehouse.visible.map{|w| [w.name, w.id]},
                                           :selected => @inventory.warehouse_id),
                        {:required => true}
        %>
        </p>
    <% end %>

    <% if @inventory.safe_attribute? 'name' %>
        <p><%= f.text_field :name, :size => 80, :maxlength => 255, :required => true %></p>
    <% end %>

    <% if @inventory.safe_attribute? 'description' %>
        <p>
          <%= f.label_for_field :description %>
          <%= link_to_function image_tag('edit.png'), '$(this).hide(); $("#issue_description_and_toolbar").show()' unless @inventory.new_record? %>
          <%= content_tag 'span', :id => "issue_description_and_toolbar", :style => (@inventory.new_record? ? nil : 'display:none') do %>
              <%= f.text_area :description,
                              :cols => 60,
                              :rows => (@inventory.description.blank? ? 10 : [[10, @inventory.description.length / 50].max, 100].min),
                              :accesskey => accesskey(:edit),
                              :class => 'wiki-edit',
                              :no_label => true %>
          <% end %>
        </p>
    <% end %>

    <div id="attributes" class="attributes">
      <%= render :partial => 'attributes' %>
    </div>

<% end %>

app/views/inventories/_form_custom_fields.html.erb
<% custom_field_values = @inventory.editable_custom_field_values %>
<div class="splitcontent">
  <div class="splitcontentleft">
    <% i = 0 %>
    <% split_on = (custom_field_values.size / 2.0).ceil - 1 %>
    <% custom_field_values.each do |value| %>
        <p><%= custom_field_tag_with_label :inventory, value %></p>
        <% if i == split_on -%>
            </div><div class="splitcontentright">
        <% end -%>
        <% i += 1 -%>
    <% end -%>
    </div>
    </div>

app/views/inventories/_form_move.html.erb
<%= labelled_fields_for :inventory, @inventory do |f| %>
    <%= error_messages_for 'inventory' %>
    <% if @inventory.safe_attribute? 'warehouse_id' %>
        <p><%= f.select :warehouse_id,
                        options_for_select(Warehouse.visible.map{|w| [w.name, w.id]},
                                           :selected => @inventory.warehouse_id),
                        {:required => true}
        %>
        </p>
    <% end %>

    <% if  @inventory.safe_attribute? 'status' %>
        <p><%= f.text_field :status, :size => 12, :required => true %> </p>
    <% end %>

    <% if  @inventory.safe_attribute? 'reason' %>
        <p><%= f.text_field :reason, :size => 12, :required => true %> </p>
    <% end %>

<% end %>

app/views/inventories/_list.html.erb
    <div class="autoscroll">
      <table class="list ">
        <thead>
        <tr>

          <% query.inline_columns.each do |column| %>
              <%= column_header(column) %>
          <% end %>
          <th></th>
        </tr>
        </thead>
        <% previous_group, first = false, true %>
        <tbody>
        <% inventories.each do |inventory| -%>
            <% if @query.grouped? && ((group = @query.group_by_column.value(inventory)) != previous_group || first) %>
                <% reset_cycle %>
                <tr class="group open">
                  <td colspan="<%= query.inline_columns.size + 2 %>">
                    <span class="expander" onclick="toggleRowGroup(this);">&nbsp;</span>
                    <%= (group.blank? && group != false) ? l(:label_none) : column_content(@query.group_by_column, inventory) %> <span class="count"></span>
                    <%= link_to_function("#{l(:button_collapse_all)}/#{l(:button_expand_all)}",
                                         "toggleAllRowGroups(this)", :class => 'toggle-all') %>
                  </td>
                </tr>
                <% previous_group, first = group, false %>
            <% end %>
            <tr id="inventory-<%= inventory.id %>" class="hascontextmenu <%= cycle('odd', 'even') %>  ">
                <%= raw query.inline_columns.map {|column| "<td class=\"\">#{column_content(column, inventory)}</td>"}.join %>

              <td>
                <% if inventory.editable_by? %>
                    <%= link_to image_tag('edit.png'), edit_inventory_path(inventory),
                                :title => l(:button_edit) %>
                    <%= link_to image_tag('move.png'), move_inventory_path(inventory),
                                :title => l(:button_move) %>
                    <%= link_to image_tag('delete.png'), inventory_path(inventory),
                                :data => {:confirm => l(:text_are_you_sure)},
                                :method => :delete,
                                :title => l(:button_delete) %>
                <% end %>
              </td> </tr>
            <% @query.block_columns.each do |column|
              if (text = column_content(column, inventory)) && text.present? -%>
                    <tr class="<%= current_cycle %>">
                      <td colspan="<%= @query.inline_columns.size + 1 %>" class=""><%= text %></td>
                    </tr>
                <% end -%>
            <% end -%>
        <% end -%>
        </tbody>
      </table>
    </div>

app/views/inventories/_new_inventory.html.erb
<% if User.current.admin? and @issue.new_record? %>
<div class="box">
  <h3>New inventory</h3>
  <% @inventory = Inventory.new %>
  <%= labelled_fields_for :inventory, @inventory do |inventory| %>
      <%= error_messages_for 'inventory' %>
      <% if @inventory.safe_attribute? 'warehouse_id' and @inventory.new_record? %>
          <p><%= inventory.select :warehouse_id,
                          options_for_select(Warehouse.visible.map{|w| [w.name, w.id]},
                                             :selected => @inventory.warehouse_id),
                          {:required => true}
          %>
          </p>
      <% end %>

      <% if @inventory.safe_attribute? 'name' %>
          <p><%= inventory.text_field :name, :size => 80, :maxlength => 255, :required => true %></p>
      <% end %>

      <% if @inventory.safe_attribute? 'description' %>
          <p>
            <%= inventory.label_for_field :description %>
            <%= link_to_function image_tag('edit.png'), '$(this).hide(); $("#issue_description_and_toolbar").show()' unless @inventory.new_record? %>
            <%= content_tag 'span', :id => "issue_description_and_toolbar", :style => (@inventory.new_record? ? nil : 'display:none') do %>
                <%= inventory.text_area :description,
                                :cols => 60,
                                :rows => (@inventory.description.blank? ? 10 : [[10, @inventory.description.length / 50].max, 100].min),
                                :accesskey => accesskey(:edit),
                                :class => 'wiki-edit',
                                :no_label => true %>
            <% end %>
          </p>
      <% end %>

      <div id="attributes" class="attributes">
        <%= render :partial => 'inventories/attributes' %>
      </div>

  <% end %>


</div>
<% end %>

app/views/inventories/edit.html.erb
<%= render partial: 'action_menu' %>
<h2>Edit Inventory</h2>
<div class="box tabular">
  <div id="all_attributes">
    <%= form_for @inventory do |f| %>
        <%= render :partial => 'form', :locals => {:f => f} %>
        <%= submit_tag l(:button_update) %>
    <% end %>
  </div>
</div>

app/views/inventories/index.html.erb
<%= render partial: 'action_menu' %>
<h2>Inventories</h2>
<%= form_tag({ :controller => 'inventories', :action => 'index', :project_id => @project },
             :method => :get, :id => 'query_form') do %>
    <div id="query_form_with_buttons" class="hide-when-print">
      <%= hidden_field_tag 'set_filter', '1' %>
      <div id="query_form_content">
        <fieldset id="filters" class="collapsible <%= @query.new_record? ? "" : "collapsed" %>">
          <legend onclick="toggleFieldset(this);"><%= l(:label_filter_plural) %></legend>
          <div style="<%= @query.new_record? ? "" : "display: none;" %>">
            <%= render :partial => 'queries/filters', :locals => {:query => @query} %>
          </div>
        </fieldset>
        <fieldset class="collapsible collapsed">
          <legend onclick="toggleFieldset(this);"><%= l(:label_options) %></legend>
          <div style="display: none;">
            <table>
              <tr>
                <td><%= l(:field_column_names) %></td>
                <td><%= render_query_columns_selection(@query) %></td>
              </tr>
              <tr>
                <td><label for='group_by'><%= l(:field_group_by) %></label></td>
                <td><%= select_tag('group_by',
                                   options_for_select(
                                       [[]] + @query.groupable_columns.collect {|c| [c.caption, c.name.to_s]},
                                       @query.group_by)
                        ) %></td>
              </tr>
              <tr>
                <td><%= l(:button_show) %></td>
                <td><%= available_block_columns_tags(@query) %></td>
              </tr>
            </table>
          </div>
        </fieldset>
      </div>
      <p class="buttons">
        <%= link_to_function l(:button_apply), 'submit_query_form("query_form")', :class => 'icon icon-checked' %>
        <%= link_to l(:button_clear), { :set_filter => 1}, :class => 'icon icon-reload'  %>
      </p>
    </div>
<% end %>

<% if @inventories.empty? %>
    <p class="nodata"><%= l(:label_no_data) %></p>
<% else %>
    <%= render :partial => 'list', :locals => {:inventories => @inventories, :query => @query} %>
    <p class="pagination"><%= pagination_links_full @entry_pages, @entry_count %></p>
<% end %>

app/views/inventories/move.html.erb
<%= render partial: 'action_menu' %>
<h2>Move Inventory</h2>
<div class="box tabular">
  <div id="all_attributes">
    <%= form_for @inventory, url: move_inventory_path(@inventory), method: :post do |f| %>
        <%= render :partial => 'form_move', :locals => {:f => f} %>
        <%= submit_tag l(:button_move) %>
    <% end %>
  </div>
</div>

app/views/inventories/new.html.erb
<%= render partial: 'action_menu' %>
<div class="box tabular">
  <div id="all_attributes">
    <%= form_for @inventory do |f| %>
        <%= render :partial => 'form', :locals => {:f => f} %>
        <%= submit_tag l(:button_create) %>
    <% end %>
  </div>
</div>

app/views/inventories/show.html.erb
<%= render :partial=> 'action_menu' %>
<div class="details">
  <div class="subject">
    <%= @inventory.name %>
  </div>
  <p>
    <%= @inventory.description %>
  </p>

</div>