config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

resources :warehouses do
  collection do
    post 'manage_roles'
    post 'delete_wu'
  end
  resources :inventories
end
resources :inventories do
  member do
    get 'move'
    post 'move'
  end
end

app/controllers/warehouses_controller.rb
class WarehousesController < ApplicationController
  unloadable

  before_filter :authorize_view, only: [:show, :index]
  before_filter :authorize_manage, except: [:show, :index]
  before_filter :get_warehouse, only:[:show, :edit, :update, :destroy]

  def index
    @warehouses = Warehouse.visible
  end

  def show
    @inventories = @warehouse.inventories
  end

  def new
    @warehouse = Warehouse.new
  end


  def create
    @warehouse = Warehouse.new
    @warehouse.name = params[:warehouse][:name]
    @warehouse.location = params[:warehouse][:location]

    if @warehouse.save
      redirect_to warehouses_path
    else
      render :new
    end

  end


  def edit
  end


  def update
    @warehouse.name = params[:warehouse][:name]
    @warehouse.location = params[:warehouse][:location]

    if @warehouse.save
      redirect_to warehouses_path
    else
      render :edit
    end
  end


  def destroy
    @warehouse.destroy
    redirect_to warehouses_path
  end


  def manage_roles
    @warehouse = WarehouseUser.where(user_id: params[:warehouse_user][:user_id]).
        where(warehouse_id: params[:warehouse_user][:warehouse_id]).first_or_initialize
    @warehouse.safe_attributes= params[:warehouse_user]
    @warehouse.save
    @user = User.find @warehouse.user_id
    @wu = WarehouseUser.where(user_id:  @user.id)
    redirect_to :back
  end

  def delete_wu
    @warehouse = WarehouseUser.find(params[:warehouse_user_id])
    @warehouse.destroy
    redirect_to :back
  end


  private

  def authorize_manage
    deny_access unless WarehouseUser.can_manage_warehouse_list?
  end

  def authorize_view
    deny_access unless WarehouseUser.can_access_warehouse_list?
  end

  def get_warehouse
    @warehouse = Warehouse.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    render_404
  end


end

app/helpers/warehouses_helper.rb
module WarehousesHelper
  def can_manage_warehouses
    @can_manage_warehouses ||= WarehouseUser.can_manage_warehouse_list?
  end

  def can_view_warehouses
    @can_view_warehouses ||= WarehouseUser.can_access_warehouse_list?
  end
end

app/views/warehouses/_action_menu.html.erb
<div class="contextual">
<% if can_manage_warehouses %>
    <%= link_to 'new warehouse', new_warehouse_path, class: 'icon icon-add' %> |
  <% end %>
  <%= link_to 'all inventories', inventories_path %>

</div>

app/views/warehouses/_form.html.erb
<% if @warehouse.safe_attribute? 'name' %>
    <p><label>Name:</label> <%= f.text_field :name, :size => 80, :maxlength => 255, :required => true %></p>
<% end %>
<% if @warehouse.safe_attribute? 'location' %>
    <p><label>Location:</label><%= f.text_field :location, :size => 80, :maxlength => 255, :required => true %></p>
<% end %>

app/views/warehouses/_membership.html.erb
<% @warehouses_users = WarehouseUser.where(user_id:  @user.id) %>
<% new_wu = WarehouseUser.new(user_id:  @user.id) %>
<% warehouses = Warehouse.order("name ASC").all %>
<div class="splitcontentleft" id="warehouses">
 <%= render(partial: 'warehouses/permission_list', locals: {warehouses_users: @warehouses_users}) %>
</div>
<div class="splitcontentright">
  <% if warehouses.any? %>
      <fieldset><legend><%=l(:label_project_new)%></legend>
        <%= form_for(new_wu, :method=> :post, :url => manage_roles_warehouses_path ) do |f| %>
            <%= f.hidden_field :user_id %>
            <%= f.select :warehouse_id, options_for_select(warehouses.map{|w| [w.name, w.id]}) %>
            <p><%= f.check_box :can_view %> Can View</p>
            <p><%= f.check_box :can_manage %> Can manage</p>
            <p><%= submit_tag l(:button_add) %></p>
        <% end %>
      </fieldset>
  <% end %>
</div>

app/views/warehouses/_permission_list.html.erb
<% if warehouses_users.present? %>
    <table class="list">
      <thead>
      <tr>
        <th>
          warehouse
        </th>
        <th>
          can View
        </th>
        <th>
          can manage
        </th>
        <th>

        </th>
      </tr>
      </thead>
      <tbody>
      <% warehouses_users.each do |wu| %>
          <tr>
            <td>
              <%= wu.warehouse %>
            </td>
            <td>
              <%= wu.can_view? %>
            </td>
            <td>
              <%= wu.can_manage? %>
            </td>
            <td>
              <%= link_to image_tag('delete.png'), delete_wu_warehouses_path(warehouse_user_id: wu.id),
                          :data => {:confirm => l(:text_are_you_sure)},
                          :method => :post,
                          :title => l(:button_delete) %>
            </td>
          </tr>
      <% end %>
      </tbody>
    </table>
<% else %>
    <p class="nodata"><%= l(:label_no_data) %></p>
<% end %>

app/views/warehouses/edit.html.erb
<h2>Edit warehouse</h2>

<div class="box tabular">
  <div id="all_attributes">
    <%= form_for @warehouse do |f| %>
        <%= render :partial => 'form', :locals => {:f => f} %>
        <%= submit_tag l(:button_update) %>
    <% end %>
  </div>
</div>

app/views/warehouses/index.html.erb
<%= render partial: 'action_menu' %>

<h2>Warehouses</h2>
<% if @warehouses.present? %>
    <table class="list">
      <thead>
      <tr>
        <th >
          #
        </th>
        <th >
          name
        </th>
        <th >
          localisation
        </th>
        <th >
        </th>
      </tr>
      </thead>
      <tbody>
      <% @warehouses.each do |warehouse| %>
          <tr>
            <td>
              <%= link_to warehouse.id, warehouse_inventories_path(warehouse) %>
            </td>
            <td>
              <%= warehouse.name %>
            </td>
            <td>
              <%= warehouse.location %>
            </td>
            <td>
              <% if warehouse.editable_by?(User.current) %>
                  <%= link_to image_tag('edit.png'), edit_warehouse_path(warehouse),
                              :title => l(:button_edit) %>
                  <%= link_to image_tag('delete.png'), warehouse_path(warehouse),
                              :data => {:confirm => l(:text_are_you_sure)},
                              :method => :delete,
                              :title => l(:button_delete) %>
              <% end %>
            </td>
          </tr>
      <% end %>
      </tbody>
    </table>
<% else %>
    <p class="nodata"><%= l(:label_no_data) %></p>
<% end %>

app/views/warehouses/manage_roles.html.erb
<h2>WarehousesController#manage_roles</h2>
<div>
  <table class="list">
    <thead>
    <tr>
      <th>
        User
      </th>
      <th>
        warehouse
      </th>
      <th>
        can View
      </th>
      <th>
        can manage
      </th>
      <th>

      </th>
    </tr>
    </thead>
    <tbody>
    <% @warehouse_users.each do |wu| %>
    <tr>
      <td>
        <%= wu.user %>
      </td>
      <td>
        <%= wu.user %>
      </td>
      <td>
        <%= wu.user %>
      </td>
      <td>
        <%= wu.user %>
      </td>
    </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/warehouses/new.html.erb
<h2>New Warehouse</h2>

<div class="box tabular">
  <div id="all_attributes">
    <%= form_for @warehouse do |f| %>
      <%= render :partial => 'form', :locals => {:f => f} %>

        <%= submit_tag l(:button_create) %>
    <% end %>
  </div>
</div>

app/views/warehouses/show.html.erb
<div class="contextual">
  <%= link_to 'new inventory', new_warehouse_inventory_path(@warehouse) %>
</div>

<h2>Warehouse</h2>

<p>
  <%= @warehouse.name %>
</p>
<p>
  <%= @warehouse.location %>
</p>
<div>

</div>
<%%>